app:
  name: CurrencyExchangeApp
  port: :3000

database:
  dsn: root:liujinshun2023@163.com@tcp(115.190.190.83:3306)/currnecy_exchange_db?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 11
  MaxOpenCons: 114

redis:
  addr: localhost:6379
  DB: 0
  Password: ""